sudo: required
services:
  - docker

before_install:
  - docker build -t rocky855/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true rocky855/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-950055239126"
  bucket_path: "frontend"
  on:
    branch: main 
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

